name: SkylliaChallenge
main: fr.euphyllia.skylliachallenge.SkylliaChallenge
loader: fr.euphyllia.skylliachallenge.SkylliaChallengeLoader
version: ${version}
api-version: 1.20.1
folia-supported: true

dependencies:
  server:
    Skyllia:
      load: BEFORE
      required: true
      join-classpath: true