name: SkylliaBank
main: fr.euphyllia.skylliabank.SkylliaBank
loader: fr.euphyllia.skylliabank.BankLoader
version: ${version}
api-version: 1.20.1
folia-supported: true

dependencies:
  server:
    PlaceholderAPI:
      join-classpath: true
      load: BEFORE
      required: false
    Skyllia:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: true
      join-classpath: true