name: SkylliaBank
main: fr.euphyllia.skylliabank.SkylliaBank
version: '1.1'
api-version: 1.20.1
folia-supported: true

dependencies:
  server:
    Skyllia:
      load: BEFORE
      required: true
      join-classpath: true