name: SkylliaChat
version: ${version}
main: fr.euphyllia.skylliachat.SkylliaChat
api-version: 1.20.1
folia-supported: true

dependencies:
  server:
    Skyllia:
      load: BEFORE
      required: true
      join-classpath: true
