rootProject.name = "Skyllia"

include("api")
include("database")
include("plugin")
// NMS Version
include("nms:v1_20_R1")
include("nms:v1_20_R2")
include("nms:v1_20_R3")
include("nms:v1_20_R4")
include("nms:v1_21_R1")
include("nms:v1_21_R2")
include("nms:v1_21_R3")
include("nms:v1_21_R4")
include("nms:v1_21_R5")
include("nms:v1_21_R6")
include("nms:v1_21_R7")
// Addons
include("addons:SkylliaOre")
//include("addons:PapiSkyllia")
//include("addons:InsightsSkyllia")
//include("addons:SkylliaChat")
//include("addons:SkylliaBank")
//include("addons:SkylliaChallenge")
// Hook
include("hook:worldedit")
include("hook:fastasyncworldedit")
include("hook:internalworld")
include("hook:canvas")
include("hook:luminol")
include("hook:essentialsx")