name: SkylliaOre
version: ${version}
main: fr.euphyllia.skylliaore.SkylliaOre
api-version: 1.20.6
folia-supported: true
loader: fr.euphyllia.skylliaore.OreLoader
authors:
  - Euphyllia

dependencies:
  server:
    Skyllia:
      load: BEFORE
      required: true
      join-classpath: true
    Oraxen:
      load: BEFORE
      required: false
      join-classpath: true
    Nexo:
      load: BEFORE
      required: false
      join-classpath: true
    CraftEngine:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true