name: SkylliaInfo
version: '${version}'
main: fr.euphyllia.skylliainfo.SkylliaInfo
api-version: 1.20.1
folia-supported: true

dependencies:
  server:
    Skyllia:
      load: BEFORE
      required: true
      join-classpath: true
    SkylliaOre:
      load: BEFORE
      required: false
      join-classpath: true
    SkylliaBank:
      load: BEFORE
      required: false
      join-classpath: true
    SkylliaValue:
      load: BEFORE
      required: false
      join-classpath: true