name: SkylliaPanel
main: fr.euphyllia.skylliapanel.SkylliaPanelPlugin
loader: fr.euphyllia.skylliapanel.SkylliaPanelLoader
version: "1.0.0"
api-version: "1.21"
folia-supported: true

dependencies:
  server:
    Skyllia:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true
