name: SkylliaOre
version: '${version}'
main: fr.euphyllia.skylliaore.Main
api-version: 1.20.1
authors: [ Euphyllia ]
folia-supported: true
loader: fr.euphyllia.skylliaore.OreLoader

dependencies:
  server:
    Skyllia:
      load: BEFORE
      required: true
      join-classpath: true
    Oraxen:
      load: BEFORE
      required: false
      join-classpath: true

