name: SkylliaGenerator
version: ${version}
main: fr.euphyllia.skylliagenerator.SkylliaGenerator
loader: fr.euphyllia.skylliagenerator.SkylliaGeneratorLoader
api-version: 1.20.5
authors: [ Euphyllia ]
folia-supported: true

dependencies:
  server:
    Skyllia:
      load: BEFORE
      required: true
      join-classpath: true
#    PlaceholderAPI:
#      load: BEFORE
#      required: false
#      join-classpath: true
