name: Build Skyllia
on:
  push:
    branches:
      - master

permissions: write-all

jobs:
  skyllia-dev:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          cache: "gradle"
          distribution: "temurin"
      - name: Configure Git User
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Permission gradlew
        run: chmod +x gradlew
      - name: Build Skyllia jar
        run: ./gradlew shadowJar
      - name: Collect jars
        run: |
          mkdir -p release
          cp build/libs/*.jar release/ || true
          cp addons/*/build/libs/*.jar release/ || true
          rm -f release/addons-*.jar
      - name: Upload Snapshot jar
        uses: actions/upload-artifact@v4
        with:
          name: Skyllia-Build
          path: release/*.jar
      - name: Create Release
        if: github.event_name != 'pull_request'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.tag }}
          name: ${{ env.project_id_b }} - ${{ github.run_number }}
          body: |
            This release is automatically compiled by GitHub Actions
            ### Commit Message
            ${{ env.commit_msg }}
          artifacts: release/*.jar
          generateReleaseNotes: true
          prerelease: ${{ env.pre }}
          makeLatest: ${{ env.make_latest }}
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: false

env:
  tag: build-${{ github.ref_name }}-${{ github.run_number }}
  project_id_b: Skyllia
  commit_id: ${{ github.sha }}
  commit_msg: ${{ github.event.head_commit.message }}
  pre: false
  make_latest: true