name: Build SkyFolia
on: [ push ]
jobs:
  skyfolia-testbuild:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      - name: Setup Java 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: "17"
          cache: "gradle"
          distribution: "temurin"
      - name: Configure Git User
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Permission gradlew
        run: chmod +x gradlew
      - name: Build SkyFolia jar
        run: ./gradlew shadowJar